### ISSUE TITLE
Crash Maps/sphere.rt (0 bounce)

### ISSUE THREAD

**Issue by Kawatwist** [Kawatwist/RaytracerV2#4]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==82441==ERROR: AddressSanitizer: SEGV on unknown address 0x00011f520000 (pc 0x00010503dedb bp 0x7ffeeabb70c0 sp 0x7ffeeabb70c0 T0)
==82441==The signal is caused by a WRITE memory access.
    #0 0x10503deda in ft_memcpy (Raytracer:x86_64+0x100001eda)
    #1 0x105049802 in texture_on_screen (Raytracer:x86_64+0x10000d802)
    #2 0x105049f9d in sub_loop (Raytracer:x86_64+0x10000df9d)
    #3 0x1050410ea in main (Raytracer:x86_64+0x1000050ea)
    #4 0x7fff70f893d4 in start (libdyld.dylib:x86_64+0x163d4)

**Comment by Kawatwist** [comment]
Color_picker do the crash (Interface will remove this error)
